# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 02:37
from __future__ import unicode_literals

from django.db import migrations, models
import mainapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180226_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, upload_to=mainapp.models.upload_image_path),
        ),
    ]
