# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-26 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_employee_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='placr_of_birth',
            new_name='place_of_birth',
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('ceo', 'CEO')], default='Employee', max_length=120),
        ),
    ]
