# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 03:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20180226_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='nationa_id',
            new_name='national_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='jop',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
