# Generated by Django 2.0.1 on 2018-02-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20180227_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jop',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
